# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cb1f77f3183db90fd2b7765e5ba2276115c1546406aee16796e5ab1d17a2c1fcf99fc679666398b811a1cea82d9b8f714ffed6752d1efe9c57996156bf602b2

test:
  secret_key_base: ed9a26f5ede844c3d853727af70743e93bad5239808c756a25c451d1961922a5e964aea6b234107966415e3ecfccbfee8cbe2670bae4aa3add8bcab2a9bdb649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
