# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e754b0bbc3dfabebb616e3adcee4840bb8ca8b4f05b79efe971bb941e8dcb35757c767a0192ca3a4c914a67cfb911d1b249bc3c608cc66be8c6c2939aa86ee7

test:
  secret_key_base: eaa10ff8f051aca50701ee11b705e5e5a2eed2cae77b0d95d624c5cb367eaf6e36cf5c260e732baae124fbead2103c92728ffb21a464732ee68b199b8091eb9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
